postsubmits:
  Maistra/test-infra:
  - name: deploy-prow-test
    decorate: true
    always_run: true
    skip_report: false
    labels:
      preset-prow-deployer: "true"
    max_concurrency: 1
    branches:
    - ^master$
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - gen-check
        - update-prow
