presubmits:
  Maistra/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  Maistra/test-infra:
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - master
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - gen-check
  Maistra/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - init
        - test
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache

## The presubmits below are for the maistra-prow-testing org, which is our test bed
  maistra-prow-testing/test-infra:
  - name: push-containers
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - master
    labels:
      preset-quay-pusher: "true"
    max_concurrency: 1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - wrapdocker
        - make
        - maistra-builder.push
        securityContext:
          privileged: true
  maistra-prow-testing/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  maistra-prow-testing/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.0"
        command:
        - make
        - init
        - test
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: integrationtests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.0"
        command:
        - make
        - init
        - test.integration.local
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
